importing ab2d-env rds
CMSgov/ab2d-bcda-dpc-platform pull request #123
Opened 2024-09-10 17:50 UTC by knavapbc

## 🎫 Ticket

https://jira.cms.gov/browse/PLT-562=3

## 🛠 Changes

no change expected

## ℹ️ Context

Changes on the .tf files to make sure after import, terrafor plan do not show any breaking changes

## 🧪 Validation
comment will show the output of terraform plan

2024-09-10 17:50 UTC, knavapbc commented
ab2d dev
```
Terraform will perform the following actions:

  # aws_db_instance.api will be updated in-place
  ~ resource "aws_db_instance" "api" {
      + apply_immediately                     = false
        id                                    = "db-2I2FGYBMWFOUXVTVAN2BNHD2HM"
        tags                                  = {
            "Name"             = "ab2d-dev-rds"
            "contact"          = "ab2d-ops@semanticbits.com"
            "cpm backup"       = "Monthly"
            "environment"      = "ab2d-dev"
            "role"             = "db"
            "terraform_module" = "data"
        }
      ~ tags_all                              = {
          + "application"      = "ab2d"
          + "business"         = "oeda"
          + "code"             = "https://github.com/CMSgov/ab2d-bcda-dpc-platform/tree/main/terraform/services/api-rds"
          + "component"        = "api-rds"
            # (7 unchanged elements hidden)
        }
        # (52 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

2024-09-10 18:33 UTC, knavapbc commented
sbx
```
Terraform will perform the following actions:

  # aws_db_instance.api will be updated in-place
  ~ resource "aws_db_instance" "api" {
      + apply_immediately                     = false
        id                                    = "db-5DGZCD7F4EKHI554AZUVKBPNNQ"
        tags                                  = {
            "Name"             = "ab2d-sbx-sandbox-rds"
            "contact"          = "ab2d-ops@semanticbits.com"
            "cpm backup"       = "Monthly"
            "environment"      = "ab2d-sbx-sandbox"
            "role"             = "db"
            "terraform_module" = "data"
        }
      ~ tags_all                              = {
          + "application"      = "ab2d"
          + "business"         = "oeda"
          + "code"             = "https://github.com/CMSgov/ab2d-bcda-dpc-platform/tree/main/terraform/services/api-rds"
          + "component"        = "api-rds"
            # (7 unchanged elements hidden)
        }
        # (52 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

2024-09-10 19:09 UTC, knavapbc commented
prod
```

  # aws_db_instance.api will be updated in-place
  ~ resource "aws_db_instance" "api" {
      + apply_immediately                     = false
        id                                    = "db-PZYY2TK3ZJ3HODBJPUZ5R4646E"
        tags                                  = {
            "Name"             = "ab2d-east-prod-rds"
            "contact"          = "ab2d-ops@semanticbits.com"
            "cpm backup"       = "Monthly"
            "environment"      = "ab2d-east-prod"
            "role"             = "db"
            "terraform_module" = "data"
        }
      ~ tags_all                              = {
          + "application"      = "ab2d"
          + "business"         = "oeda"
          + "code"             = "https://github.com/CMSgov/ab2d-bcda-dpc-platform/tree/main/terraform/services/api-rds"
          + "component"        = "api-rds"
            # (7 unchanged elements hidden)
        }
        # (52 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

2024-09-10 19:39 UTC, gsf requested changes
Please add the check-terraform-fmt job back into the api-rds-plan workflow and confirm successful plan via that check.

2024-09-11 19:04 UTC, merged

2024-09-11 19:09 UTC, gsf commented on .github/workflows/api-rds-plan.yml
>      permissions:
AB2D also includes a "prod-test" environment with a database. The matrix below will need to be extended with the environment.

2024-09-11 19:09 UTC, gsf commented on terraform/services/api-rds/main.tf
> +      test = "ab2d-east-prod-test"
The ab2d test environment database is "ab2d-east-impl". See my comment above for handling of the ab2d-east-prod-test database.