BCDA-7898: Add bcda check for opt-out-import
CMSgov/ab2d-bcda-dpc-platform pull request #84
Opened 2024-06-04 19:39 UTC by austincanada

Adds a check for bcda in order to correctly name the opt-out-import function module.

## 🎫 Ticket

https://jira.cms.gov/browse/BCDA-7898

## 🛠 Changes

Added a check for the app variable in order to change the name within the opt-out-import module.

## ℹ️ Context for reviewers

Making it so that BCDA is properly supported for opt-out import.

## ✅ Acceptance Validation

Not sure how to properly test.

## 🔒 Security Implications

- [ ] This PR adds a new software dependency or dependencies.
- [ ] This PR modifies or invalidates one or more of our security controls.
- [ ] This PR stores or transmits data that was not stored or transmitted before.
- [ ] This PR requires additional review of its security implications for other reasons.

If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge this PR without his approval.

2024-06-05 16:42 UTC, gfreeman-navapbc approved these changes
LGTM

2024-06-05 17:29 UTC, gsf requested changes

2024-06-05 19:47 UTC, kyeah commented on terraform/services/opt-out-import/main.tf
> +  name        = var.app == "bcda" ? "opt-out-import" : local.full_name
@austincanada I meant the `handler` name below, not the lambda name itself 😄

(the name here = the lambda name in AWS. the handler name below is the name of the packaged binary that we are going to upload as a zip file from the bcda-app workflow.)

2024-06-05 19:50 UTC, oluwolenpbc approved these changes

2024-06-07 16:01 UTC, gsf commented on terraform/services/opt-out-import/main.tf
> +  handler = var.app == "ab2d" ? "gov.cms.ab2d.optout.OptOutHandler" : var.app == "bcda" ? "opt-out-import" : "bootstrap"
Would you mind switching this to a map as we did with `db_sg_name`, etc. in the locals? I think it makes sense to do so once each of the three APIs has its own value.

2024-06-07 16:49 UTC, gsf approved these changes
Looks good!

2024-06-07 17:14 UTC, merged